### ISSUE TITLE
Save numeric matrix to PGEN formatted file?

### ISSUE THREAD

**Issue by biona001** [OpenMendel/PGENFiles.jl#7]
I have a numeric matrix (genotype dosages) that I'd like to save to a standard format. 
Does either PGENFiles.jl or BGEN.jl support this operation? 

If not, I can try to implement it if I can get a rough idea of how to do it (assuming it's not too hard).

**Comment by kose-y** [comment]
Not yet. It will be more straightforward in PGEN format, as BGEN data are stored in probability triplets for 0/0, 0/1, and 1/1. Maybe Plink 2 has a default method to convert dosages into probability triplets.

**Comment by biona001** [comment]
Okay! In the next few days I'll familiarize myself with the PGEN format, and try to write a writer that can save dosage information.
